### Create a Profile
POST http://localhost:8080/api/profile/create
Content-Type: application/json

{
  "bio": "Aspiring software developer",
  "skills": ["Java", "Spring Boot"],
  "resumeLink": "https://example.com/resume.pdf"
}

### Get all Profiles
GET http://localhost:8080/api/profile/getAll


### Create a Profile with studentNumber
POST http://localhost:8080/api/profile/create
Content-Type: application/json

{
  "studentNumber": "230716873",
  "bio": "Aspiring software developer",
  "skills": ["Java", "Spring Boot"],
  "resumeLink": "https://example.com/resume.pdf"
}

### Get profile by studentNumber
GET http://localhost:8080/api/profile/student/230716873